export const categories = [
  "Technology",
  "Education",
  "Lifestyle",
  "Entertainment",
  "Health & Wellness",
  "Business & Finance",
  "Travel",
  "Food & Recipes",
  "Personal Development",
  "Science",
  "Environment & Sustainability",
  "Politics & Society",
  "Sports & Fitness",
  "Art & Culture",
  "Fashion & Beauty",
  "DIY & Crafts",
  "Parenting & Family",
  "History",
  "Literature & Books",
  "Gaming",
];
